### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [PerfectFreeze/PFStepper#1]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by Cee** [comment]
WIP! 😊

**Comment by lfarah** [comment]
Thanks! 🎉

**Comment by Cee** [comment]
@lfarah Compatible with Swift 3.0 now! Checkout 1dbdc1a. 😊
